### PR TITLE
 add merge_reasons management command 

### PR DESCRIPTION
**Pull request by willemarcel**

### CODE REVIEW

**Comment by batpad** [comment]
Could I make a suggestion? To make `merge_reason` or so a method on SuspiciousReason, and then perhaps have it executable either as a management command or via an API call that is restricted to admin users? My hunch is this might be a recurring need and it might be nice to eventually have some UI for this.

Although this looks great as well :-)

**Comment by willemarcel** [comment]
Hi, @batpad! Thanks for the idea! The worry I have with making an api endpoint is that maybe it will be a operation that would take a lot of time from the database and that would request the API access to be stopped while we are executing it... What do you think? One of the operations we need to execute is to merge `New mapper <5 mapping days` into `New mapper`, what will affect 90,323 changesets.

**Comment by batpad** [comment]
@willemarcel good point :-)

You probably should go ahead and merge this -- but slightly separately, would this be more efficient / quicker if one managed to encapsulate the DB operation into a single UPDATE operation?

I can imagine that the SQL that needs to be executed would be something like:

`UPDATE changeset_changeset_reasons SET reason=14 WHERE reason=12` <-- I'm abbreviating of course, but you get the point? Seems like the current code would generate individual updates for every row: https://github.com/willemarcel/osmcha-django/pull/145/files#diff-3cf11657b9184cb66a673fa466ab097aR24 and that would likely be significantly slower.

If its a single UPDATE operation, I imagine that actually updating ~100,000 rows at a time should not actually be a problem / take anything beyond 2-3 seconds - and since it's an admin-only operation, it may still be fine to expose in the API?

Of course, management command may also make sense considering the sensitivity of the operation and the fact that it will be non-trivial to "undo". But if it's not too hard, maybe nice to see if it can be performed as a single UPDATE - I'll try poking around the ORM a bit as well..

**Comment by willemarcel** [comment]
@batpad good idea! I think the SQL UPDATE could solve it. I'll try to do that way and try to filter only the changesets that don't have the reason we want to apply, otherwise it would generate duplicated reasons for a changeset.

**Pull request merged**
