### PR TITLE
Add unique constraint to SuspiciousReason name and make migrations

### PR DESCRIPTION
**Pull request by amishas157**
Getting multiple entries for Suspicion Reason name in osmcha-django when a new reason is created. Therefore added unique constraint to `name` . 

cc @willemarcel

### CODE REVIEW

**Comment by willemarcel** [comment]
Hi @amishas157 ! Thanks for the PR!!! I should have started the project with the `unique=True` in the name field! I tested here and we need to assure the database doesn't have duplicated SuspicionReasons names, otherwise the migration will fail. I'm going write a data migraton to do that, using the `.merge` classmethod of `SuspicionReason` model. Does that sound ok?

cc: @batpad

**Comment by amishas157** [comment]
@willemarcel That sounds great to go. 👍 Thanks 🙇

**Comment by willemarcel** [comment]
Hi @amishas157 ! I had written two migrations in the `restapi` branch that were conflicting with your migrations. So I had to discover a way to merge them without make the two branches database incompatible. But now I believe it's ok!

@batpad I just realized that the merge method of SuspicionReasons doesn't update the `Features` that have relationship with it. Is it the desired behaviour?

**Comment by batpad** [comment]
> @batpad I just realized that the merge method of SuspicionReasons doesn't update the Features that have relationship with it. Is it the desired behaviour?

No, that sounds like a bug, @willemarcel :(

**Comment by willemarcel** [comment]
@batpad fixed it with https://github.com/willemarcel/osmcha-django/commit/16ce2a1339f9673eaf5e7813ba1ddd9ccc463272

**Pull request merged**
